### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by wexi** [jaraco/backports.functools_lru_cache#12]
Hi Jaraco,
Please note that your package, which is a required by the popular matplotlib, **seems to be** broken.
Kindly advise how to fix.
Thanks, Enoch.

```
Installing collected packages: backports.functools-lru-cache
Successfully installed backports.functools-lru-cache-1.5
enoch@dome:~/private/gpanes$ python
Python 2.7.14 (default, Sep 23 2017, 22:06:14) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> try:
...     from functools import lru_cache
... except ImportError:
...     from backports.functools_lru_cache import lru_cache
... 
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
ImportError: No module named functools_lru_cache
```

**Comment by webknjaz** [comment]
@wexi you probably didn't install it into the env you're running python interpreter from.

**Comment by jaraco** [comment]
Hi @wexi . That issue might happen for a number of scenarios:

- there's another, older 'backports' package installed and taking ownership of the namespace
- (as webknjaz says) if you don't have the package properly installed in the same environment where you're trying to use it.
- the namespace package wasn't installed properly
- there's another backports directory masking the namespace

But it works for me:

```
~ $ python2.7 -m pip install backports.functools_lru_cache
Collecting backports.functools_lru_cache
  Using cached https://files.pythonhosted.org/packages/03/8e/2424c0e65c4a066e28f539364deee49b6451f8fcd4f718fefa50cc3dcf48/backports.functools_lru_cache-1.5-py2.py3-none-any.whl
Installing collected packages: backports.functools-lru-cache
Successfully installed backports.functools-lru-cache-1.5
~ $ python2.7 -c "from backports.functools_lru_cache import lru_cache" && echo "worked!"
worked!
```

You can start to troubleshoot by running `pip list | grep backports` and see if maybe there are other old backports installed and upgrade or uninstall it.

If that doesn't help, try uninstalling all backports packages and see what's claiming the backports package name with `python -c "import backports; print(backports.__file__)"`. Trace that file and maybe delete whatever is supplying it.

If that doesn't get you straight, try replicating your issue on a clean Linux host. Maybe build a Docker image that replicates the issue. If you can provide steps to replicate the issue, we can almost certainly help resolve the issue.

Good luck. I'm going to close this ticket as there's unlikely a bug with the project, but feel free to respond back with more details.
