### ISSUE TITLE
Document need of setuptools >= 36.7.0

### ISSUE THREAD

**Issue by idgserpro** [jaraco/backports.functools_lru_cache#13]
`backports.functools_lru_cache` 1.6+ uses setup_requires in setup.cfg. This is only supported from `setuptools` 36.7.0. See:

https://github.com/pypa/setuptools/blob/a0fe403c141369defacf12dccbdc01634bbcb1da/CHANGES.rst#v3670

**Comment by jaraco** [comment]
Fixed in 0bf3d43d97d5466fddac708e7ca38ba95281c6e7.
