### ISSUE TITLE
The package doesn't report its license

### ISSUE THREAD

**Issue by jaraco** [jaraco/backports.functools_lru_cache#3]
Originally reported by: **BitBucket: [eli.boyarski](http://bitbucket.org/eli.boyarski), GitHub: [eli.boyarski](http://github.com/eli.boyarski)**

---

> > yolk -l backports.functools-lru-cache -f license

prints

> backports.functools-lru-cache (1.0.3)
> 
>   License: UNKNOWN

---
- Bitbucket: https://bitbucket.org/jaraco/backports.functools_lru_cache/issue/3

**Comment by jaraco** [comment]
_Original comment by_: **Jason R. Coombs (BitBucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

---

I looked into this, but it looks like all yolk does is print a metadata field from the package, but [according to the docs](https://docs.python.org/2/distutils/setupscript.html#additional-meta-data), the license field is only for use when the license isn't in a trove classifier field. In the latest backports.functools-lru-cache (1.1), the license is advertised in the metadata in the trove classifiers:

```
$ curl https://pypi.python.org/pypi/backports.functools_lru_cache/json -so - | jq '.info.classifiers | map(select(startswith("License")))[0]'
"License :: OSI Approved :: MIT License"
```

I did try testing to see what yolk does yield for 1.1, but yolk seems to be buggy. I couldn't install it on Python 3 and on Python 2, it failed to find the package:

```
$ python -m virtualenv --python python2.7 issue3
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in issue3/bin/python
Installing setuptools, pip, wheel...done.
$ issue3/bin/pip install yolk backports.functools_lru_cache
Collecting yolk
Collecting backports.functools-lru-cache
  Downloading backports.functools_lru_cache-1.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./issue3/lib/python2.7/site-packages (from yolk)
Installing collected packages: yolk, backports.functools-lru-cache
Successfully installed backports.functools-lru-cache-1.1 yolk-0.4.3
$ issue3/bin/yolk -l backports.functools_lru_cache -f license
backports.functools_lru_cache is not installed.
$ . issue3/bin/activate
(issue3)$ yolk -l backports.functools_lru_cache -f license
backports.functools_lru_cache is not installed.
```

I get the same error with backports.functools_lru_cache installed by easy_install.

In any case, I've verified that since the 1.1 release, the package reports its license according to the prescription by distutils, so I'm considering this resolved.

**Comment by eli-b** [comment]
Thanks for specifying a license in newer versions, and congratulations on the recent move to GitHub :)

Notice that to list metadata for packages with '_' in their name, you have to use '-' instead, like I did in my original report.

I would still request that you list the license directly in `setup.py`, to enable yolk to print it. I have automated tests that make sure I only use packaged with approved licenses.

**Comment by eli-b** [comment]
I've opened https://github.com/eli-b/backports.functools_lru_cache/pull/1
