### ISSUE TITLE
__init__.py missing

### ISSUE THREAD

**Issue by PeterSlickers** [jaraco/backports.functools_lru_cache#7]
I have installed 'backports.functools_lru_cache' via pip. Package 'backports.functools_lru_cache' is the first 'backports' package on my computer. Installation finishes without error but the newly create directory '~/lib/python2.7/site-packages/backports' is missing a `'__init__.py'` file. Without this file, import of 'backports.functools_lru_cache' fails in python applications.

```
python
Python 2.7.12 (default, Jun 29 2016, 08:18:26) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import backports.functools_lru_cache
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named backports.functools_lru_cache
```

Work-around:
`touch ~/lib/python2.7/site-packages/backports/__init__.py`

**Comment by jaraco** [comment]
That behavior is normal for pip. It removes the namespace package module file. What I don't recall is what functionality is meant to replace the file. On Python 3.3, those are discovered naturally. I'm guessing I won't be able to replicate this but I'll try later.

**Comment by jaraco** [comment]
```
jaraco@elektra:~$ env/bin/python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more info
rmation.
>>> import backports.functools_lru_cache
>>> 
jaraco@elektra:~$ ls env/lib/python2.7/site-packages/backports
functools_lru_cache.py  functools_lru_cache.pyc
jaraco@elektra:~$ cat env/lib/python2.7/site-packages/backport
s.functools_lru_cache-1.2.1
backports.functools_lru_cache-1.2.1.dist-info/
backports.functools_lru_cache-1.2.1-py3.5-nspkg.pth
jaraco@elektra:~$ cat env/lib/python2.7/site-packages/backport
s.functools_lru_cache-1.2.1-py3.5-nspkg.pth 
import sys, types, os;p = os.path.join(sys._getframe(1).f_loca
ls['sitedir'], *('backports',));ie = os.path.exists(os.path.jo
in(p,'__init__.py'));m = not ie and sys.modules.setdefault('ba
ckports', types.ModuleType('backports'));mp = (m or []) and m.
__dict__.setdefault('__path__',[]);(p not in mp) and mp.append
(p)
jaraco@elektra:~$ 
```

Seems to be working for me. It's the .nspkg file that's providing access to the namespace package. Maybe look to see if you have something different, or maybe try getting a later version of pip.

**Comment by PeterSlickers** [comment]
In my use case, the .pth  installed with your python package seems to be ignored. You may try this to reproduce the failure. I assume that you still have the 'env' in your HOME:

```
export PYTHONPATH=env/lib/python2.7/site-packages
/usr/bin/python -c 'import backports'
```

Now go into your virtual env and install package 'backports.ssl-match-hostname':

```
cd env
bin/pip install backports.ssl-match-hostname
```

Then move back into your HOME and retry the import with the python of your system:

```
/usr/bin/python -c 'import backports'
```

This time, import should be successful.

I am not really familiar with details of pip, setuptools and proper packaging. It is obvious that the problem arises because I use PYTHONPATH. Python will not search for .pth files in directories specified in PYTHONPATH. 

I was just naively expecting that every python module has a `'__init__.py'`(which is often just an empty file).  The backports package in pypi is somehow a strange thing since it cannot be installed by itself. But in my understanding, https://pypi.python.org/pypi/backports/ requires, that  subpackages should create `'__init__.py'`.

The above is a simplification of my real use case. I am not using 'backports.functools_lru_cache'  directly in any of my programming projects. It is just pulIed in by pylint.  Pylint is installed to one central place (with pip), and I use this pylint with all of my programming projects. Pylint emits an ugly warning, if import of 'backports.functools_lru_cache' fails:

```
Problem importing module variables.py: No module named backports.functools_lru_cache
```

**Comment by jaraco** [comment]
> the .pth installed with your python package seems to be ignored.

According to [the docs](https://docs.python.org/3.5/library/site.html), a .pth file must exist in one of four directories, so you wouldn't expect it to be honored if it's only in PYTHONPATH.

The problem isn't with this package, but with the packaging tool you're using and the way you're expecting it to work.

`pip` by design expects all packages to be installed in a site-packages and relies on the -nspkg.pth files to satisfy the namespace packages (such as `backports` is).

Your best bet is that if you're using a virtual environment (as it appears you are in `env`) is just invoke Python from there.

```
env/bin/python2.7 -c "import backports"
```

Or even better, use Python 3.3 or later, which I believe has support for namespace packages without requiring the `__init__.py` or `-nspkg.pth` files.

**Comment by jaraco** [comment]
Oh, and I should mention that this package does supply the `__init__.py` file, which you can [find here](https://github.com/jaraco/backports.functools_lru_cache/blob/master/backports/__init__.py). It's the `pip` installer that removes that file during installation. You might find that if you were to install with `easy_install` that you have better luck.
